### ISSUE TITLE
Data format for HybriK - short Query

### ISSUE THREAD

**Issue by Dipankar1997161** [boreshkinai/hybrik-transformer#2]
Hey @boreshkinai,

I actually read your paper on Hybrik Transformer.  I had 1-2 query which I hope gets answered. 

For training Hybrik, we require the 3d keypoints, right?  what other things would we need.? 
I am creating my own dataset, and would test on this.  So it's important for me to know the format to follow.

I look forward to hear from you

**Comment by boreshkinai** [comment]
Hey @Dipankar1997161 thanks for your interest. Basically Hybrik accepts different types of datasets. Some of them contain 2d keypoints (e.g. COCO) and some others contain 3d keypoints (e.g. H36M). H36M also contains SMPL beta parameters for pose shape, unlike other 3D datasets. 

The bottom line is if you have a lot of 3D labels for 2D images you can definitely use it as one of the datasets to train the model. If you want to use your dataset as the only source of training data for Hybrik, then it's a different story - things get more complicated.

**Comment by Dipankar1997161** [comment]
> Hey @Dipankar1997161 thanks for your interest. Basically Hybrik accepts different types of datasets. Some of them contain 2d keypoints (e.g. COCO) and some others contain 3d keypoints (e.g. H36M). H36M also contains SMPL beta parameters for pose shape, unlike other 3D datasets.
> 
> The bottom line is if you have a lot of 3D labels for 2D images you can definitely use it as one of the datasets to train the model. If you want to use your dataset as the only source of training data for Hybrik, then it's a different story - things get more complicated.

Actually it's a new dataset which I created having close to a million images. It has all the smpl parameters, 2d and 3d keypoints and also thr camera parameters.

I was wondering if theirs a specific format to maintain while passing the data as input. You can consider there are 24 3d keypoints and smpl poses and shapes per image. QUESTION -- So do I require anything else? Or just 3d keypoints, smpl poses, and shapes, 2d and camera values should be enough to train Hybrik?

As you mentioned there, there's no harm in using h36m + my own dataset to train. But if it's possible to just train or even fine tune, that works too. All I wish to achieve is that the dataset I provide is valid for 2d and 3d human motion analysis

**Comment by boreshkinai** [comment]
It looks like you are all set for success. I think those are all the ingredients you need to successfully train the model. Let me know if you have additional questions.

**Comment by boreshkinai** [comment]
I think you are basically all set, but the dataloaders of course assume specific formatting of the input files and the original data from H36M are preprocessed in a certain way. As a next step, you will have to take a closer look at the dataloaders. I think looking at one for H36M might be very helpful:

https://github.com/boreshkinai/hybrik-transformer/blob/master/HybrIK/hybrik/datasets/h36m_smpl.py

**Comment by Dipankar1997161** [comment]
> I think you are basically all set, but the dataloaders of course assume specific formatting of the input files and the original data from H36M are preprocessed in a certain way. As a next step, you will have to take a closer look at the dataloaders. I think looking at one for H36M might be very helpful:
> 
> https://github.com/boreshkinai/hybrik-transformer/blob/master/HybrIK/hybrik/datasets/h36m_smpl.py

Another thing I wish to know. If Hybrik only based for h36m datasets? Like the end results are 17 keyppint detection or what? 
Because most of my data are openpose based like 18-25 keypoints and fitted to 24 smpl joints. 
So I am slightly confused on whether Hyrbik is only for 17 keyppint detection or ?

**Comment by boreshkinai** [comment]
No, the ML part of the model predicts the shape parameters and rotation quaternions of SMPL model. So the end result is the fully parameterized SMPL model. They use a separate 17-point SMPL regressor to be able to deal with the datasets that are based on 17 points. However, the main backbone is really a 24-point SMPL. Makes sense?

**Comment by Dipankar1997161** [comment]
> No, the ML part of the model predicts the shape parameters and rotation quaternions of SMPL model. So the end result is the fully parameterized SMPL model. They use a separate 17-point SMPL regressor to be able to deal with the datasets that are based on 17 points. However, the main backbone is really a 24-point SMPL. Makes sense?

hey @boreshkinai, Thanks for informing me about it.  I was training on the **original hybrik** with 24 smpl_joints, 17 h36m_joints , poses, thetas and every parameters.. in the similar way as h36m processed files.,  but I got a weird tensor size error..

    the leaf_thetas is torch.Size([160, 3, 3])
    torch.Size([32, 24, 3, 3])
    the rot_mat shape is torch.Size([32, 5, 3, 3])
    the rot_parent indices is torch.Size([32, 2, 3, 3])
    terminate called without an active exception
      0%|                                                                                                                                                                                          | 0/57 [02:31<?, ?it/s]
    Traceback (most recent call last):
      File "/home/ndip/HybrIK/scripts/train_smpl.py", line 398, in <module>
        main()
      File "/home/ndip/HybrIK/scripts/train_smpl.py", line 246, in main
        mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
        return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
        while not context.join():
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 163, in join
        raise ProcessRaisedException(msg, error_index, failed_process.pid)
    torch.multiprocessing.spawn.ProcessRaisedException: 
    
    -- Process 0 terminated with the following error:
    Traceback (most recent call last):
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
        fn(i, *args)
      File "/home/ndip/HybrIK/scripts/train_smpl.py", line 346, in main_worker
        loss, acc17 = train(opt, train_loader, m, criterion, optimizer, writer)
      File "/home/ndip/HybrIK/scripts/train_smpl.py", line 61, in train
        output = m(inps, trans_inv, intrinsic_param, root, depth_factor, None)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
        else self._run_ddp_forward(*inputs, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
        return self.module(*inputs, **kwargs)  # type: ignore[index]
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ndip/HybrIK/hybrik/models/simple3dposeBaseSMPL24.py", line 337, in forward
        output = self.smpl.hybrik(
      File "/home/ndip/HybrIK/hybrik/models/layers/smpl/SMPL.py", line 263, in hybrik
        vertices, new_joints, rot_mats, joints_from_verts = hybrik(
      File "/home/ndip/HybrIK/hybrik/models/layers/smpl/lbs.py", line 357, in hybrik
        rot_mats, rotate_rest_pose = batch_inverse_kinematics_transform_naive(
      File "/home/ndip/HybrIK/hybrik/models/layers/smpl/lbs.py", line 874, in batch_inverse_kinematics_transform_naive
        rot_mat_chain[:, indices] = torch.matmul(
    RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1
-------------

**I am not quiet able to understand, what can arise this.. is this Dataset error? or it seems like GPU or distributed training error..??    I have 2 GPUS** 

I checked my dataset thoroughly but couldn't find any issues in this as it is 100% similar structure to h36m process files.   
**Could this be due to the shape of dataset keys??**

I am unable to figure out the reason for this... 

If you can help me on this, I would be really grateful🙏

-------------
The code where this error occurs is 

        if leaf_thetas is not None:
            leaf_cnt = 0
            leaf_rot_mats = leaf_thetas.view([batch_size, 5, 3, 3])
        idx_levs = [
            [0],
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
            [12, 13, 14],
            [15, 16, 17],
            [18, 19, 10],
            [20, 21, 11],
            [22, 23],
            [24, 25, 26, 27, 28]
        ]
        if leaf_thetas is not None:
            idx_levs = idx_levs[:-1]
        
        for idx_lev in range(1, len(idx_levs)):
            indices = idx_levs[idx_lev]
            if idx_lev == len(idx_levs)-1:
                # leaf nodes
                if leaf_thetas is not None:
                    rot_mat = leaf_rot_mats[:, :, :, :]
                    print(f'the rot_mat shape is {rot_mat.shape}')
                    print(f'the rot_parent indices is {rot_mat_chain[:, parents[indices]].shape}')
                    rotate_rest_pose[:, indices] = rotate_rest_pose[:, parents[indices]] + torch.matmul(
                        rot_mat_chain[:, parents[indices]], 
                        rel_rest_pose[:, indices]
                    )
    
                    rot_mat_chain[:, indices] = torch.matmul(
                        rot_mat_chain[:, parents[indices]], 
                        rot_mat
                    )
                    rot_mat_local[:, indices] = rot_mat

**Comment by Dipankar1997161** [comment]
@boreshkinai,
so I used your repo and it trains on 24 joints as well. however, the pipe gets broken.. 

the system on which the code is running is linux, but I used ssh to connect from my home Mac. 
the current batch size is 4 with world_size as 2, since I have only 2 gpu

could you tell me a potential fix for the error?  any changes in the code?

this is the script to run

    python train_smpl.py --cfg configs/hybrik_transformer_smpl24.yaml --seed 100000 --nThreads 8 --launcher pytorch --rank 0 --exp-id 2 --dist-url tcp://134.109.5.228:23455


output

      ############# Starting Epoch 0 | LR: 0.0 #############
        0%|                                                                                                                                                                                        | 0/1800 [00:00<?, ?it/s][W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
      [W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
      loss: 2.24222533 | accuvd29: 0.0006 | acc17: 0.0000: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1800/1800 [06:10<00:00,  4.86it/s]
      Train-0 epoch | loss:2.24222533 | acc:0.0000
      /home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
        warnings.warn(_create_warning_msg(
      /home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
        warnings.warn(_create_warning_msg(
       17%|█████████████████████████████▌                                                                                                                                                  | 19/113 [00:49<00:24,  3.89it/s]client_loop: send disconnect: Broken pipe
      dipankarnandi@MBP-14-M2-Dipankar-Nandi ~ %

**Comment by boreshkinai** [comment]
@Dipankar1997161 
Sorry I never used the distributed url option to train it. Maybe this could be the problem? My workflow was the following:
- I build and run docker container
- Go inside docker container
- Once inside the docker, launch training session using something like this: 
`./scripts/train_smpl.sh experiment_name ./configs/hybrik_transformer_smpl24.yaml`

**Comment by Dipankar1997161** [comment]
> @Dipankar1997161 Sorry I never used the distributed url option to train it. Maybe this could be the problem? My workflow was the following:
> 
> * I build and run docker container
> * Go inside docker container
> * Once inside the docker, launch training session using something like this:
>   `./scripts/train_smpl.sh experiment_name ./configs/hybrik_transformer_smpl24.yaml`

@boreshkinai, ok this is clear to me. I was able to run training script without docker.

I have another question in regards to validation.

I run the validate_smpl.py with the pre-trained resnet model and passed a sample dataset and got the following error

    ##### Testing on NTOP #####
      0%|                                                                                                                                                                                        | 0/3600 [00:04<?, ?it/s]
      0%|                                                                                                                                                                                        | 0/3600 [00:04<?, ?it/s]
    Traceback (most recent call last):
      File "/home/ndip/workspace/hybrik-transformer/HybrIK/validate_smpl.py", line 305, in <module>
        main()
      File "/home/ndip/workspace/hybrik-transformer/HybrIK/validate_smpl.py", line 237, in main
        mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
        return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
        while not context.join():
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 163, in join
        raise ProcessRaisedException(msg, error_index, failed_process.pid)
    torch.multiprocessing.spawn.ProcessRaisedException: 
    
    -- Process 1 terminated with the following error:
    Traceback (most recent call last):
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
        fn(i, *args)
      File "/home/ndip/workspace/hybrik-transformer/HybrIK/validate_smpl.py", line 300, in main_worker
        gt_tot_err = validate_gt(m, opt, cfg, gt_val_dataset_ntop, heatmap_to_coord, opt.batch)
      File "/home/ndip/workspace/hybrik-transformer/HybrIK/validate_smpl.py", line 99, in validate_gt
        output = m(
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
        else self._run_ddp_forward(*inputs, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
        return self.module(*inputs, **kwargs)  # type: ignore[index]
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ndip/workspace/hybrik-transformer/HybrIK/hybrik/models/hybrikTransformerSMPL24.py", line 614, in forward
        x0 = self.preact(x)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ndip/workspace/hybrik-transformer/HybrIK/hybrik/models/layers/Resnet.py", line 139, in forward
        x = self.maxpool(self.relu(self.bn1(self.conv1(x))))  # 64 * h/4 * w/4
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 138, in forward
        self._check_input_dim(input)
      File "/home/ndip/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 416, in _check_input_dim
        raise ValueError(f"expected 4D input (got {input.dim()}D input)")
    ValueError: expected 4D input (got 3D input)

**4D Input??**. what does that even suppose to mean here?? 
My val dataset as mentioned has 3d smpl and 3d human3.6m joints as well as their 2d equivalent.  
smpl: x,y,z in the form of a list with shape 72,0
h36m: shape 51,0

What does 4D input mean here?? another dimension of what value?

**Comment by Dipankar1997161** [comment]
https://github.com/boreshkinai/hybrik-transformer/blob/b19c35ba92dd62061e0892033ff0760a1ef36028/HybrIK/hybrik/datasets/h36m_smpl.py#L30
@boreshkinai,
The evaluation joints 17 are the human3.6m joints, but why are they arranged in such a fashion?  6,5,4,1,2,3........ and so on

Why not 0-16 like how it is done for coco?

**Comment by Dipankar1997161** [comment]
> @Dipankar1997161 Sorry I never used the distributed url option to train it. Maybe this could be the problem? My workflow was the following:
> 
> * I build and run docker container
> * Go inside docker container
> * Once inside the docker, launch training session using something like this:
>   `./scripts/train_smpl.sh experiment_name ./configs/hybrik_transformer_smpl24.yaml`

@boreshkinai,
Hey, I validated on my data and as expected the metrics are pretty high. But I was wondering for training the MPJPE metrics never decreases.. 

Could you tell me, does the smpl_joints need to be in camera coordinate system first before being used??? 
Mine are mostly in world coordinate system..

**Comment by boreshkinai** [comment]
@Dipankar1997161 I would look at a few examples, but I think this code is basically assuming that the root position and camera parameters are provided externally. I think the dataset was build so that root position for each pose is 0, at least this is what I remember for H36M data.
